### ISSUE TITLE
/list needs work

### ISSUE THREAD

**Issue by PacksGamingHD** [AvalancheYT/FreedomCore#11]
When you do list it shows as this:
Connected players: [[Rank]Player]

So basically theres a [] surrounding the online players

**Comment by MrImmaculate** [comment]
I am assigning @ThePheonixBlader to this. Let's test your skill.

**Comment by PacksGamingHD** [comment]
I tried to change quite a bit of things with no avail, so good luck taah!

**Comment by PacksGamingHD** [comment]
Taah has no clue lol

**Comment by AvalancheYT** [comment]
@ThePheonixBlader, you know you can recode it...

**Comment by AvalancheYT** [comment]
Further testing is not necessary, brackets is the part of the list, not a bug.

**Comment by PacksGamingHD** [comment]
Its a bug and it needs to be fixed

**Comment by AvalancheYT** [comment]
@PacksGamingHD, please don't override my input. I really don't mind how it is.

**Comment by PacksGamingHD** [comment]
I do and probably many future server owners will
