### ISSUE TITLE
bug: motd

### ISSUE THREAD

**Issue by PacksGaming4K** [AvalancheYT/FreedomCore#16]
with the motd it says the " and " at the end of the MOTD so you'd have to do something like .replace("\"\, ""

**Comment by AvalancheYT** [comment]
"" doesn't affect the motd, it is just a string quote

**Comment by PacksGaming4K** [comment]
no it does in the server list

**Comment by AvalancheYT** [comment]
Then, you are doing it wrong. Mine doesn't do that.

**Comment by PacksGaming4K** [comment]
pastern me your config
