### ISSUE TITLE
Retiring

### ISSUE THREAD

**Issue by AvalancheYT** [AvalancheYT/FreedomCore#17]
You know what?! I fucking give up, all of you just don't listen to me. I lost my plugin just for that.
THANK YOU! You made me pissed off.

THIS PLUGIN IS SHIT

**Comment by PacksGaming4K** [comment]
Ok! Can I take over the project

**Comment by AvalancheYT** [comment]
Fuck off

**Comment by PacksHD** [comment]
Project continued at: github.com/PacksDevelopment/FreedomCore

**Comment by Adaptified** [comment]
You give up too quickly, @AvalancheYT. It is why you will always be an amateur until you learn to grow up.

**Comment by AvalancheYT** [comment]
I am sorry about my behaviour. I got really mad since my brother broke my source code on my netbeans (which was completed, everything was working)
