### ISSUE TITLE
[DEVELOPER] Spot filled up

### ISSUE THREAD

**Issue by AvalancheYT** [AvalancheYT/FreedomCore#5]
These spot is taken by @PacksGamingHD and @MrImmaculate.
- [x] I will add them to collaborator once I have upload the latest commitment

NOTE: You guys, Collaborators, can only make commitments into Development branch. Once development branch is finished and tested. We will merge it into master branch. Master branch is untouched. If master branch is touched, it will simply reverted by me.

**Comment by PacksGamingHD** [comment]
how come there are commits to the master branch? the master branch has more added to RankManager when that should've been in development

**Comment by AvalancheYT** [comment]
Ahh thanks for the notice. Fixed.
