### ISSUE TITLE
BukkitLib

### ISSUE THREAD

**Issue by AvalancheYT** [AvalancheYT/FreedomCore#7]
Add BukkitLib:
- [ ] Fix configuration loading
- [ ] clean commands

**Comment by PacksGamingHD** [comment]
No, but if your using an old file that uses BukkitLib (not aero) there may be some compatibility issues porting it over to aero

**Comment by AvalancheYT** [comment]
Well, we can convert over to BukkitLib... Pro/Cons?

**Comment by PacksGamingHD** [comment]
Then no, I don't see any issues

**Comment by AvalancheYT** [comment]
@ThePheonixBlader @MrImmaculate, your opinion?

**Comment by PacksGamingHD** [comment]
(off topic: see https://github.com/AvalancheYT/FreedomCore/issues/8)

**Comment by AvalancheYT** [comment]
Second thought, I am starting to make this plugin compatible with BukkitLib

**Comment by PacksGamingHD** [comment]
Why? Just use Aero. Its newer, and that is what will be used from then on

**Comment by AvalancheYT** [comment]
@PacksGamingHD, according to last test with aero, all it does is giving error, but I got more experience with BukkitLib.

**Comment by AvalancheYT** [comment]
Third thought, we don't need this anymore. I have resolved the configuration loading.

**Comment by MrImmaculate** [comment]
Please link me to where you fixed it! @AvalancheYT

**Comment by AvalancheYT** [comment]
e4ae8a4

**Comment by Adaptified** [comment]
Thanks!
