### ISSUE TITLE
FreedomCore folder doesn't load

### ISSUE THREAD

**Issue by PacksGamingHD** [AvalancheYT/FreedomCore#8]
If you try to load FreedomCore it doesn't load the FreedomCore folder.

The only time it creates a folder is when you execute /admin, then it will create admin.yml It doesn't create the config.yml

Somehow, it still manages to load the data from the config.yml (look at /fc for the forums) and theres also some compatibility issues with /list and the ranks.

I also propose we change the super admin, telnet admin and senior admin to simply super, telnet and senior. We also need to add an owner rank

**Comment by AvalancheYT** [comment]
This will go with BukkitLib, replacing FConfig.java

**Comment by PacksGamingHD** [comment]
Reopened

**Comment by AvalancheYT** [comment]
Closed in e4ae8a4
